### ISSUE TITLE
Prepare data

### ISSUE THREAD

**Issue by icewindi** [wurenkai/MHA-UNet#1]
Hi. I'm having trouble preparing the data. Can you provide the preparation method for NormalSkin and Kaggle95. I will be grateful.

**Comment by wurenkai** [comment]
Hi. We have uploaded the process and code for processing negative sample data used for testing. This is the process that applies to any negative sample processing. We hope this is helpful to you.

#0 The negative dataset is without segmentation labels. It is possible to generate the same number of all-black labels as the original image in the following way:

python generate_black.py

It should be noted that the number of generated images in the generate_black.py file needs to be modified.

#1 When the same number of all-black labels are available, the following command is executed to generate test data:

python Prepare_Neg_test.py

It should be noted that the number of images in the Prepare_Neg_test.py file needs to be modified.

**Comment by alkpi** [comment]
Thank you for your reply.

**Comment by icewindi** [comment]
Thank you for your reply.
